### ISSUE TITLE
Needed to cast html content via template literals

### ISSUE THREAD

**Issue by FelixEhuan** [TinkoffCreditSystems/ng-dompurify#32] opened 2019-12-19 00:00 UTC
I tried to implement the dompurify in order to use inline styles for a blog that i created, the data was obtained directly from the server:
```
    this.service.getBlog(url).pipe(
        take(1),
       ) .subscribe(  res => this.data = res; );
```
and passed via 
```
 <div class="blog" @items>
        <h1>{{data.title | uppercase}}</h1>
        <div class="blog__content" [innerHTML]="data.html"></div>
   </div>
```
the app.module is implemented this way: 
```
...
  providers: [
      {
      provide: DomSanitizer,
      useClass: NgDompurifyDomSanitizer,
    },
    {
      provide: SANITIZE_STYLE,
      useValue: ɵ_sanitizeStyle,
    },
  ],
...
```
for some reason the sanitizer for [innerHTML] was deleting my inline styles but when i reproduce it in a stackblitz, the sanitizer works correctly.

https://stackblitz.com/edit/dompurify-example

i found that the solution was wrap the html property in a template literal ( as i did it in stackblitz): 

```
    this.service.getBlog(url).pipe(
        take(1),
       ) .subscribe(  res => {
        this.data = res; 
        this.html = `${this.data.html}`;
        });

  ...
 <div class="blog" @items>
        <h1>{{data.title | uppercase}}</h1>
        <div class="blog__content" [innerHTML]="html"></div>
   </div>
```
Do you know why doesn't work with the object property option? It works as intended or it's some type of bug?

Cheers!

**Comment by waterplea** [comment] 2019-12-19 18:38
Definitely sounds strange. I'm out of town, will look into it when I get back or @MarsiBarsi will take a look. In the meantime, please share the actual HTML you tried so I can reproduce it as close as I can.

**Comment by waterplea** [comment] 2020-02-19 13:43
Closing since to no details were provided. Feel free to comment if you still need help.

**Closed by waterplea** 2020-02-19 13:43 UTC
